name: Deploy to Firebase Hosting
on: [push]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install TypeScript
        run: npm install -g typescript
      - name: Compile TS to JS
        run: tsc public/app.ts --target es5 --outFile public/app.js
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_EEIGHAA_EBCD1 }}'
          channelId: live
          projectId: eeighaa-ebcd1
